### ISSUE TITLE
Investigate adding optional ApplyOn argument to entity search

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-xt-grid#5]
_From @tobiasleibner on February 23, 2015 8:43_

For the PeriodicGridView, the periodic neighbor will always be on the boundary, so searching the whole GridView should be a waste of time. I tried adding an optional ApplyOn-Argument to the entity search and using EntityInLevelSearch(gridview, ApplyOn::BoundaryEntities) in the PeriodicGridView. This improved test_periodicview from 6000 ms to 3700 ms on my machine, but creating a PeriodicGridView with 300x300 Entities regressed from 30s to around 90s. Need to investigate where this difference comes from.

_Copied from original issue: wwu-numerik/dune-stuff#41_

**Comment by renemilk** [comment]
Could you add a minimal example to show the difference, @tobiasleibner ?

**Comment by tobiasleibner** [comment]
I investigated the performance with and without the ApplyOn argument again and I do not think it is worth the effort and complexity. The code with ``ApplyOn::BoundaryEntities`` is hardly faster and sometimes even slower than the current version, because the hasBoundaryIntersections() call seems to be quite costly. I also tried to iterate only over the border ``PartitionSet`` (for codim > 0), which also is only slightly faster.
